baseURL = "http://example.org/"
languageCode = "en-us"
title = "My portfolio"
theme = "basic"

[params]
author = "Nick"
description = "My portfolio site"

gh_url = "https://api.github.com/users"
gh_user = "torvalds"